#
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
[tool.setuptools]
packages = ['api', 'gui', 'pdk', 'common', 'fileio', 'backend', 'resources']
py-modules = ['revinit']
[project]
name = "revolution-eda"
version = "0.4.0"
description = 'Revolution EDA is a new generation integrated circuit design environment.'
readme = "README.md"
classifiers = ["Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
]
keywords = ["electronic", "design", "schematic"]
dependencies = ["PySide6>=6.4.2",
    "quantiphy>=2.19",
]
requires-python = ">=3.10"
[project.urls]
Homepage = "https://github.com/eskiyerli/revedaRelease"
[project.scripts]
reveda = "gui.appWindow:main"